FROM clfoundation/sbcl:2.5.10 AS builder

ENV QUICKLISP_ADD_TO_INIT_FILE=true
ENV QUICKLISP_DIST_VERSION=latest

WORKDIR /app
COPY . .

RUN /usr/local/bin/install-quicklisp && make cli

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/bin/migratum .
ENTRYPOINT ["./migratum"]
